apiVersion: v1
data:
  MONGO_INITDB_ROOT_PASSWORD: MTIwOA==
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==
  MONGO_PASS: MTIwOA==
  MONGO_USER: cm9vdA==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Secret","apiVersion":"v1","metadata":{"name":"payment-microservice-db-secret","creationTimestamp":null},"data":{"MONGO_INITDB_ROOT_PASSWORD":"MTIwOA==","MONGO_INITDB_ROOT_USERNAME":"cm9vdA==","MONGO_PASS":"MTIwOA==","MONGO_USER":"cm9vdA=="}}
  creationTimestamp: "2021-02-04T08:56:31Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:MONGO_INITDB_ROOT_PASSWORD: {}
        f:MONGO_INITDB_ROOT_USERNAME: {}
        f:MONGO_PASS: {}
        f:MONGO_USER: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:type: {}
    manager: kubectl-create
    operation: Update
    time: "2021-02-04T08:56:31Z"
  name: payment-microservice-db-secret
  namespace: default
  resourceVersion: "51868"
  uid: 8b071ff2-f0ce-45d2-b4d8-7b0a7761a973
type: Opaque
